### ISSUE TITLE
Report nodes as "unreported" if last report is more that 2 hours old

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/prometheus-puppetdb-exporter#1]
That's the way the Puppetboard does it and allows to find nodes were puppet is not running like it should.

**Comment by cryptobioz** [comment]
e65fb047ef94f577e00fb192d79cd1e0957183b4 should fix your issue. The default value for setting a node as _unreported_ is 2 hours after the last report but this can be modified via the option `--unreported-node`.
